---
title: '2018-10-03'
output: html_document
---
```{r}
library(stringr)
library(readr)
studentID <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/studentID.csv")
```

```{r}
str_sub(studentID$學號,5,6)
```


```{r}
str_sub(studentID$學號,5,6) -> aa
table(aa)
```

```{r}
str_c(letters,LETTERS)
str_c(letters,LETTERS,sep="-")
str_c("lowercase: ", letters, ", capital: ", LETTERS)
```



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
githubData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/githubData.csv")
```

```{r}
githubData[c(2,3,4),] -> sampleGithub
str_c(sampleGithub$`GitHub username`,
      sampleGithub$`GitHub repo name`)
str_c("https://github.com/",
      sampleGithub$`GitHub username`,
      "/",
      sampleGithub$`GitHub repo name`)
```

```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/course-107-1-programming-for-data-science/master/data/%E7%AC%AC%E4%B8%89%E5%B1%86%E7%B6%93%E6%BF%9F%E6%92%AD%E5%AE%A2%E7%AB%B6%E8%B3%BD%E5%8F%83%E8%B3%BD%E4%BD%9C%E5%93%81%E6%8A%95%E7%A5%A8%E7%B5%90%E6%9E%9C%E6%A8%A3%E6%9C%AC%20-%20Sheet1.csv")
```

```{r}
fruits <- c(
  "apples and oranges and pears and bananas",
  "pineapples and mangos and guavas"
)
str_split_fixed(fruits, " and ", 3)
str_split_fixed(fruits, " and ", 4)
```

```{r}
str_split_fixed(filmVotingData$請選擇你最喜歡的影片二部,",",3)->bb
dim(bb)
```

```{r}
cc<-c(bb)
cc
table(cc)
```

```{r}
head(filmVotingData$請選擇你最喜歡的影片二部)
```


```{r}
library(stringr)
str_split_fixed(filmVotingData$請選擇你最喜歡的影片二部,","n=3) ->splitResult
```
```{r}
str_c(splitResult) ->arrayResult
head(arraryResult)
```

```{r}
a<-c("A, B","B, C")
a
str_split_fixed(a,", ", n=3)->b
str_c(b)->c
c
table(b)
b
```

```{r}
library(googlesheets)
```

```{r}
gs_auth(new_user = TRUE)
```








